"""Versions of an output. Each time an output's text changes (the AI writes it, a human edits it,
the AI writes it again) a new version is saved, and the old ones are kept unchanged.

outputs.content_json always holds the latest version, so downloads and the Results page always use
it. output_versions holds every version, so older ones can still be viewed.
"""

import copy

from app.db import Output, OutputVersion, utc_now

ORIGIN_LABELS = {"ai": "Written by AI", "human": "Edited by human", "regenerated": "Regenerated by AI",
                 # Stage 8: outputs in Indian languages
                 "translated": "Machine translated", "retranslated": "Translated again",
                 "operator": "Written by the Operator",  # the SMS of an emergency alert
                 # the "Shorter / More formal / Simpler" buttons
                 "shorter": "Made shorter by AI", "formal": "Made more formal by AI", "simpler": "Made simpler by AI"}


def current_version(output: Output) -> int:
    """The latest version number. Outputs finished before Stage 5 have no number yet: they are version 1."""
    return output.version or (1 if output.content_json else 0)


def save_version(db, output: Output, content: dict, origin: str, by=None) -> OutputVersion:
    """Make `content` the newest version of `output` (origin: ai | human | regenerated).
    by: the user who edited it (human edits); None for versions the AI wrote."""
    if output.content_json and not output.versions:
        # An output from before Stage 5: keep what it said as version 1 before changing it.
        db.add(OutputVersion(output=output, version=current_version(output), origin=output.origin or "ai",
                             content_json=copy.deepcopy(output.content_json), quality_json=output.quality_json,
                             quality_score=output.quality_score, created_at=output.finished_at or utc_now()))
    number = current_version(output) + 1
    version = OutputVersion(output=output, version=number, origin=origin, content_json=copy.deepcopy(content),
                            created_by=by.id if by is not None else None)
    db.add(version)
    output.content_json, output.version, output.origin = copy.deepcopy(content), number, origin
    return version


def version_summary(version: OutputVersion) -> dict:
    return {
        "version": version.version,
        "origin": version.origin,
        "origin_label": ORIGIN_LABELS.get(version.origin, version.origin),
        "quality_score": version.quality_score,
        "created_at": version.created_at,
    }
